spring.application.name=jewellery-backend

# PostgreSQL Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# PostgreSQL Configuration
#spring.datasource.url=jdbc:postgresql://localhost:5432/business_db
#spring.datasource.username=postgres
#spring.datasource.password=Shyamnagar123#

spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server
server.port=${PORT:8080}
#server.port=8080

jwt.secret=Jw8kP2mQ9xL4vN7sR5tY3uI6oP8aS1dF4gH7jK2Siddh